version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo "Installing dependencies..."
      - composer install --no-dev --optimize-autoloader
  build:
    commands:
      - echo "Build completed"
  post_build:
    commands:
      - echo "Deploying to EC2"
      - rsync -avz -e "ssh -o StrictHostKeyChecking=no -i ec2-key.pem" ./ ec2-user@<EC2-IP>:/var/www/html
artifacts:
  files:
    - '**/*'
